### ISSUE TITLE
Does anything need to be connected to Pin 35

### ISSUE THREAD

**Issue by romanwroclawski** [danilopinotti/esp-battery18650-stats#2]
@danilopinotti the instructions are not clear if anything from the battery needs to be connected on pin 35 of the board? Is the existence of the pin on the board enough to facilitate functionality?

**Comment by danilopinotti** [comment]
Hello @romanwroclawski!

Pin 35 in the documentation is the pin where the lib will read the battery stats, not the pin that connects the battery.

PS: Was used pin 35 as an example because [LILYGO-T-Energy (T18)](https://github.com/LilyGO/LILYGO-T-Energy/blob/master/T18v3.0.jpg) uses this pin as ADC Battery.
The ADC Pin may be another number according to your Devkit. I encourage you to look for the ADC Battery pin in the Datasheet of your Devkit model.

**Comment by romanwroclawski** [comment]
@danilopinotti thank you for the quick reply. Regardless of the pin, nothing needs to be connected to the pin to take the measurement, correct? All of the connections are handled internally on the IC?

**Comment by danilopinotti** [comment]
> @danilopinotti thank you for the quick reply. Regardless of the pin, nothing needs to be connected to the pin to take the measurement, correct? All of the connections are handled internally on the IC?

@romanwroclawski I don't connect anything in this pin to avoid conflicts. I really don't know if this is a rule.
